### ISSUE TITLE
Known issue: https://github.com/openshift/installer/issues/3028

### ISSUE THREAD

**Issue by DustinTrap** [RedHatOfficial/ocp4-vsphere-upi-automation#12] opened 2020-04-10 14:22 UTC
Hello!

I wanted to share that your scripts seems to be working well. However, I am stuck with what appears to be an upstream OCP Installer problem. https://github.com/openshift/installer/issues/3028.

I wanted you to know in case you see any way to solve for it.

Thank you!

**Comment by vchintal** [comment] 2020-04-10 16:35
Sorry my friend, I have installed OpenShift a dozen times in the past two months testing and never was unsuccessful. The message does show up for a good amount of time till the masters are up and in a good shape to form the etcd quorum with bootstrap but the installation moves forward. 

I am sorry but I have to close this issue as it cannot be duplicated on my end (and other colleagues who have been testing this repo with me) and also because it doesn't relate to this repo directly.

**Closed as completed by vchintal** 2020-04-10 16:35 UTC

**Comment by DustinTrap** [comment] 2020-04-10 16:42
I let the first cluster run for 15 hours overnight. I rebuilt a second time and it's two hours with no changes. Guess I'll keep pursuing this through the OCP Install team. Have a good weekend!

**Comment by DustinTrap** [comment] 2020-04-10 18:45
This is an issue with the install script. What happened is that the DHCP server had given out the wrong lease to a node. Thus, the machine configs applied no longer matched the vm\dns names. This caused the whole install to fail.

The corrective step was to delete the dhcp lease, and then restart the dhcp service. Then, reattempting the install succeeded.

I suggest you consider lowering the DHCP service timout to 60 seconds in the future.

**Comment by vchintal** [comment] 2020-04-10 18:50
Still can’t understand why the issue is raised with this repo. As mentioned
earlier, I have run both repos countless times in my homelab and not once I
have run into this issue. This repo isn’t responsible for anything DHCP. If
you have set the MAC/IP correctly and matching with what helper has you
should never run into this issue.
-- 
Vijay Chintalapati
